name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint:check
      
      - name: Run TypeScript type check
        run: npm run type-check
      
      - name: Build check
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
